[package]
name = "ml-toolkit-for-zed"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }

